### PR TITLE
US 24/27/28 admin merchant enable/disable

### LINKED ISSUE #22: 27. Admin Merchant Enable/Disable
As an admin,
When I visit the admin merchants index (/admin/merchants)
Then next to each merchant name I see a button to disable or enable that merchant.
When I click this button
Then I am redirected back to the admin merchants index
And I see that the merchant's status has changed

### LINKED ISSUE #23: 28. Admin Merchants Grouped by Status
As an admin,
When I visit the admin merchants index (/admin/merchants)
Then I see two sections, one for "Enabled Merchants" and one for "Disabled Merchants"
And I see that each Merchant is listed in the appropriate section

### PR DESCRIPTION
**Pull request by yainporter**
Sorry, I was coming and going as I was working on this and forgot to branch. All three of these User Stories had to do with the admin/merchants#index so I did them all. 

**Notable Changes:**
- Added in a has_many relation with Merchants and Transactions, tested in merchant_spec
- Added in a new column :status to the Merchants table

I pulled down and merged with main before pushing, so hopefully nothing is broken, please check and let me know if there are any issues/questions.

Thanks!

### CODE REVIEW

**Review by n0rdie — COMMENTED** [review]
In the merchant model, does the status enum need to have integers? From what I remember status should be stored as integer.

This is what I had from my Adopt Don't Shop pet application
enum status: {'In Progress': 0, 'Pending': 1, 'Accepted': 2, 'Rejected': 3}

**Comment by yainporter** [comment]
> In the merchant model, does the status enum need to have integers? From what I remember status should be stored as integer.
> 
> This is what I had from my Adopt Don't Shop pet application enum status: {'In Progress': 0, 'Pending': 1, 'Accepted': 2, 'Rejected': 3}

I don't think the Merchant class has a status?

**Review by mdarl17 — COMMENTED** [review]
Hi Yain, I left a comment responding to your question about using an enum for Merchant status - you are correct that it should be implemented like 'adopt' with { integer: string } syntax.  - Matt

**Review by mdarl17 — CHANGES_REQUESTED** [review]
Hi Yain, I left a comment responding to your question about using an enum for Merchant status - you are correct that it should be implemented like 'adopt' with { integer: string } syntax.  - Matt

**Comment by yainporter** [comment]
I've fixed the enum status: for Merchant

**Review by SamPuttman — APPROVED** [review]
Everything looks great to me! I absolutely love your tests. They're so clean and concise!

**Pull request merged**
